// Generated by Copilot
#ifndef CONFIG_H
#define CONFIG_H

#include <Arduino.h>

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Hardware Pin Definitions
// ⚪ NOTE: GPIO numbers for ESP8266 NodeMCU board
// ═══════════════════════════════════════════════════════════════════════════

// 🔵 INFO: I2C Bus pins for PCA9685 and MPU6050
constexpr uint8_t PIN_SDA = D2; // GPIO4
constexpr uint8_t PIN_SCL = D1; // GPIO5

// 🔵 INFO: Digital input for bottom retroreflective sensor
constexpr uint8_t PIN_BOTTOM_SENSOR = D5; // GPIO14

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: I2C Device Addresses
// ═══════════════════════════════════════════════════════════════════════════

constexpr uint8_t PCA9685_ADDRESS = 0x40;
constexpr uint8_t MPU6050_ADDRESS = 0x68;

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: LED Configuration
// ⚪ NOTE: PCA9685 provides 16 channels, we use 10 for stair steps
// ═══════════════════════════════════════════════════════════════════════════

constexpr uint8_t LED_COUNT = 10;
constexpr uint8_t LED_FIRST_CHANNEL = 0;
constexpr uint8_t LED_LAST_CHANNEL = LED_COUNT - 1;

// 🔵 INFO: PWM resolution and frequency
constexpr uint16_t PWM_RESOLUTION = 4096; // 12-bit resolution
constexpr uint16_t PWM_MAX_VALUE = PWM_RESOLUTION - 1;
constexpr uint16_t PWM_FREQUENCY = 1600; // Hz, flicker-free for LEDs

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Motion Detection Configuration
// ═══════════════════════════════════════════════════════════════════════════

// 🔵 INFO: MPU6050 accelerometer sensitivity thresholds
constexpr float ACCEL_THRESHOLD_DEFAULT = 1.5f; // m/s² above baseline
constexpr float ACCEL_THRESHOLD_MIN = 0.5f;
constexpr float ACCEL_THRESHOLD_MAX = 5.0f;

// 🔵 INFO: Sensor debounce and timeout settings
constexpr unsigned long SENSOR_DEBOUNCE_MS = 200;
constexpr unsigned long EFFECT_TIMEOUT_DEFAULT = 30000; // 30 seconds
constexpr unsigned long EFFECT_TIMEOUT_MIN = 5000;      // 5 seconds
constexpr unsigned long EFFECT_TIMEOUT_MAX = 300000;    // 5 minutes

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Lighting Effect Timing
// ⚪ NOTE: All timing values in milliseconds
// ═══════════════════════════════════════════════════════════════════════════

constexpr unsigned long EFFECT_STEP_DELAY_DEFAULT = 200; // ms between steps
constexpr unsigned long EFFECT_STEP_DELAY_MIN = 50;
constexpr unsigned long EFFECT_STEP_DELAY_MAX = 2000;

constexpr unsigned long FADE_DURATION_DEFAULT = 300; // ms for fade in/out
constexpr unsigned long FADE_DURATION_MIN = 100;
constexpr unsigned long FADE_DURATION_MAX = 2000;

constexpr unsigned long KNIGHT_RIDER_SPEED = 100; // ms per step for startup effect

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Brightness Configuration
// ⚪ NOTE: Percentage values (0-100)
// ═══════════════════════════════════════════════════════════════════════════

constexpr uint8_t BRIGHTNESS_DEFAULT = 80;
constexpr uint8_t BRIGHTNESS_MIN = 10;
constexpr uint8_t BRIGHTNESS_MAX = 100;

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: WiFi Configuration
// ⚪ NOTE: Access Point mode settings for initial setup
// ═══════════════════════════════════════════════════════════════════════════

constexpr const char *AP_SSID = "StairLight_Setup";
constexpr const char *AP_PASSWORD = "stairlight123";
constexpr unsigned long WIFI_CONNECT_TIMEOUT = 30000;    // 30 seconds
constexpr unsigned long WIFI_RECONNECT_INTERVAL = 60000; // 1 minute

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Web Server Configuration
// ═══════════════════════════════════════════════════════════════════════════

constexpr uint16_t WEB_SERVER_PORT = 80;
constexpr const char *OTA_HOSTNAME = "stairlight";

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Time and Scheduling Configuration
// ═══════════════════════════════════════════════════════════════════════════

constexpr const char *NTP_SERVER = "pool.ntp.org";
constexpr long NTP_OFFSET_DEFAULT = 3600;              // UTC+1 (Central Europe)
constexpr unsigned long NTP_UPDATE_INTERVAL = 3600000; // 1 hour

// 🔵 INFO: Daylight disable feature - default schedule
constexpr uint8_t DISABLE_START_HOUR = 8; // 8 AM
constexpr uint8_t DISABLE_END_HOUR = 20;  // 8 PM

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: EEPROM Configuration
// ⚪ NOTE: Memory layout for persistent storage
// ═══════════════════════════════════════════════════════════════════════════

constexpr uint16_t EEPROM_SIZE = 512;
constexpr uint16_t EEPROM_CONFIG_START = 0;
constexpr uint32_t EEPROM_MAGIC_NUMBER = 0x5354414C; // "STAL" in hex

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: System Configuration
// ═══════════════════════════════════════════════════════════════════════════

constexpr unsigned long SERIAL_BAUD_RATE = 115200;
constexpr unsigned long LOOP_UPDATE_INTERVAL = 50;     // Main loop rate in ms
constexpr unsigned long STATUS_UPDATE_INTERVAL = 5000; // Debug output rate

// ⚪ NOTE: Maximum string lengths for WiFi credentials
constexpr uint8_t MAX_SSID_LENGTH = 32;
constexpr uint8_t MAX_PASSWORD_LENGTH = 64;

#endif // CONFIG_H
