// Generated by Copilot
#ifndef LEDS_H
#define LEDS_H

#include <Arduino.h>
#include "config.h"
#include "storage.h"

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: LED Effect State Enumeration
// ⚪ NOTE: Tracks current animation state for non-blocking operation
// ═══════════════════════════════════════════════════════════════════════════

enum class EffectState
{
  IDLE,         // No effect running, LEDs off or at static brightness
  KNIGHT_RIDER, // Startup animation
  WALK_UP_ON,   // Lighting up from bottom to top
  WALK_DOWN_ON, // Lighting up from top to bottom
  HOLD,         // All LEDs on, waiting for timeout
  WALK_UP_OFF,  // Turning off from bottom to top
  WALK_DOWN_OFF // Turning off from top to bottom
};

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: LED Module Public Functions
// ═══════════════════════════════════════════════════════════════════════════

/*
  Function: initLEDs
  Purpose:  Initialize PCA9685 PWM driver and set all LEDs to off
  Reason:   Must be called during setup before controlling LEDs
  Returns:  true if PCA9685 initialized successfully, false on error
*/
bool initLEDs();

/*
  Function: updateLEDs
  Purpose:  Process current animation frame and update LED states
  Reason:   Should be called frequently in main loop for smooth effects
*/
void updateLEDs();

/*
  Function: startEffect
  Purpose:  Begin a lighting effect based on motion direction
  Reason:   Called when motion sensor detects someone on stairs
*/
void startEffect(EffectType type, const EffectConfig &config);

/*
  Function: startKnightRider
  Purpose:  Run the startup animation (back-and-forth sweep)
  Reason:   Visual feedback that system is powered on and ready
*/
void startKnightRider();

/*
  Function: stopAllEffects
  Purpose:  Immediately stop current effect and turn off all LEDs
  Reason:   Used for emergency stop or configuration changes
*/
void stopAllEffects();

/*
  Function: setGlobalBrightness
  Purpose:  Set master brightness multiplier for all effects
  Reason:   Allows user to dim entire system without changing each effect
*/
void setGlobalBrightness(uint8_t brightness);

/*
  Function: setEffectTimeout
  Purpose:  Configure how long LEDs stay on before fade-out
  Reason:   User-adjustable via web interface
*/
void setEffectTimeout(unsigned long timeoutMs);

/*
  Function: isEffectRunning
  Purpose:  Check if any animation is currently active
  Reason:   Prevents new triggers from interrupting current effect
  Returns:  true if effect in progress, false if idle
*/
bool isEffectRunning();

/*
  Function: getCurrentState
  Purpose:  Get current effect state for debug/display
  Reason:   Enables real-time monitoring via web interface
*/
EffectState getCurrentState();

/*
  Function: setAllLEDs
  Purpose:  Directly set all LEDs to same brightness (for testing)
  Reason:   Useful for diagnostics and manual control
*/
void setAllLEDs(uint8_t brightness);

/*
  Function: showBottomSensorInstall
  Purpose:  Turn all LEDs on for bottom sensor installation mode
  Reason:   Visual feedback when sensor is triggered during installation
*/
void showBottomSensorInstall(bool triggered);

/*
  Function: showMotionInstall
  Purpose:  Display VU meter effect based on motion strength
  Reason:   Visual feedback for motion sensor calibration (0-100%)
*/
void showMotionInstall(uint8_t strength);

#endif // LEDS_H
