// Generated by Copilot
#ifndef SENSORS_H
#define SENSORS_H

#include <Arduino.h>
#include "config.h"

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Motion Direction Enumeration
// ⚪ NOTE: Determines which lighting effect to trigger
// ═══════════════════════════════════════════════════════════════════════════

enum class MotionDirection
{
  NONE = 0,
  WALK_UP,  // Detected at bottom sensor (going up)
  WALK_DOWN // Detected at top MPU6050 (going down)
};

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Sensor Status Structure
// ⚪ NOTE: Used for debug output and web interface
// ═══════════════════════════════════════════════════════════════════════════

struct SensorStatus
{
  float accelX;
  float accelY;
  float accelZ;
  float accelMagnitude;
  bool bottomSensorActive;
  bool motionDetected;
  unsigned long lastTriggerTime;
};

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Sensor Module Public Functions
// ═══════════════════════════════════════════════════════════════════════════

/*
  Function: initSensors
  Purpose:  Initialize MPU6050 accelerometer and configure bottom sensor pin
  Reason:   Must be called during setup before reading sensor data
  Returns:  true if MPU6050 initialized successfully, false on error
*/
bool initSensors();

/*
  Function: calibrateMPU6050
  Purpose:  Establish baseline accelerometer readings for motion detection
  Reason:   Compensates for mounting angle and device variations
*/
void calibrateMPU6050();

/*
  Function: updateSensors
  Purpose:  Read current sensor values and update internal state
  Reason:   Should be called frequently in main loop for responsive detection
*/
void updateSensors();

/*
  Function: checkMotion
  Purpose:  Determine if motion detected and which direction
  Reason:   Core logic for triggering appropriate lighting effects
  Returns:  MotionDirection enum indicating detected motion type
*/
MotionDirection checkMotion();

/*
  Function: setAccelThreshold
  Purpose:  Adjust motion detection sensitivity
  Reason:   Allows user customization via web interface
*/
void setAccelThreshold(float threshold);

/*
  Function: setDebounceDelay
  Purpose:  Set minimum time between motion triggers
  Reason:   Prevents rapid re-triggering from sensor noise
*/
void setDebounceDelay(unsigned long delayMs);

/*
  Function: getSensorStatus
  Purpose:  Retrieve current sensor readings for debug/display
  Reason:   Enables real-time monitoring via web interface
*/
SensorStatus getSensorStatus();

/*
  Function: resetLastTrigger
  Purpose:  Clear the last trigger timestamp
  Reason:   Used when effect completes to allow immediate re-trigger
*/
void resetLastTrigger();

#endif // SENSORS_H
