// Generated by Copilot
#ifndef SERIALCMD_H
#define SERIALCMD_H

#include <Arduino.h>
#include "config.h"

// Forward declaration
struct SystemConfig;

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Serial Command Interface
// ⚪ NOTE: Interactive configuration and testing via USB serial
// ═══════════════════════════════════════════════════════════════════════════

// 🔵 INFO: Initialize serial command handler
void initSerialCmd();

// 🔵 INFO: Process incoming serial commands
// ⚪ NOTE: Call this in main loop to handle keyboard input
void updateSerialCmd(SystemConfig &config);

// 🔵 INFO: Print help menu
void printHelp();

// 🔵 INFO: Print current configuration
void printConfig(const SystemConfig &config);

#endif // SERIALCMD_H
