// Generated by Copilot
#ifndef STORAGE_H
#define STORAGE_H

#include <Arduino.h>
#include "config.h"

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Effect Type Enumeration
// ⚪ NOTE: Four distinct lighting effects based on motion direction
// ═══════════════════════════════════════════════════════════════════════════

enum class EffectType : uint8_t
{
  WALK_UP = 0,      // Bottom to top, lights turn on
  WALK_DOWN = 1,    // Top to bottom, lights turn on
  WALK_UP_OUT = 2,  // Bottom to top, lights turn off
  WALK_DOWN_OUT = 3 // Top to bottom, lights turn off
};

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Effect Configuration Structure
// ⚪ NOTE: Each effect type can be configured independently
// ═══════════════════════════════════════════════════════════════════════════

struct EffectConfig
{
  uint16_t stepDelay;    // Milliseconds between lighting each step
  uint16_t fadeDuration; // Milliseconds for smooth fade in/out
  uint8_t brightness;    // Brightness percentage (0-100)
  uint8_t overlap;       // Number of steps to light simultaneously
  bool enabled;          // Whether this effect is active
};

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: WiFi Configuration Structure
// ═══════════════════════════════════════════════════════════════════════════

struct WiFiConfig
{
  char ssid[MAX_SSID_LENGTH + 1];
  char password[MAX_PASSWORD_LENGTH + 1];
  bool useHomeWiFi; // If false, only use AP mode
};

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Scheduling Configuration Structure
// ⚪ NOTE: Allows disabling lights during specific hours (e.g., daylight)
// ═══════════════════════════════════════════════════════════════════════════

struct ScheduleConfig
{
  bool enabled;           // Master enable for scheduling
  uint8_t disableStart;   // Hour to disable (0-23)
  uint8_t disableEnd;     // Hour to re-enable (0-23)
  int16_t timezoneOffset; // Seconds from UTC
};

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Sensor Configuration Structure
// ═══════════════════════════════════════════════════════════════════════════

struct SensorConfig
{
  float accelThreshold;        // Motion detection sensitivity
  unsigned long effectTimeout; // How long to wait before fade-out
  unsigned long debounceDelay; // Minimum time between triggers
};

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Complete System Configuration Structure
// ⚪ NOTE: All persistent settings stored in EEPROM
// ═══════════════════════════════════════════════════════════════════════════

struct SystemConfig
{
  uint32_t magicNumber; // Validation marker for EEPROM
  uint16_t version;     // Config structure version

  // 🔵 INFO: Effect configurations for all four effect types
  EffectConfig walkUp;
  EffectConfig walkDown;
  EffectConfig walkUpOut;
  EffectConfig walkDownOut;

  // 🔵 INFO: System-wide settings
  WiFiConfig wifi;
  ScheduleConfig schedule;
  SensorConfig sensor;

  bool debugMode;           // Enable real-time status updates
  uint8_t globalBrightness; // Master brightness override
};

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Storage Module Public Functions
// ═══════════════════════════════════════════════════════════════════════════

/*
  Function: initStorage
  Purpose:  Initialize EEPROM and load configuration or set defaults
  Reason:   Must be called during system startup before accessing config
*/
void initStorage();

/*
  Function: loadConfig
  Purpose:  Read configuration from EEPROM into provided structure
  Reason:   Retrieves user settings that persist across power cycles
  Returns:  true if valid config found, false if using defaults
*/
bool loadConfig(SystemConfig &config);

/*
  Function: saveConfig
  Purpose:  Write configuration structure to EEPROM
  Reason:   Persists user changes across power cycles
  Returns:  true if save successful, false on error
*/
bool saveConfig(const SystemConfig &config);

/*
  Function: resetToDefaults
  Purpose:  Restore factory default settings and save to EEPROM
  Reason:   Provides recovery option if configuration becomes corrupted
*/
void resetToDefaults(SystemConfig &config);

/*
  Function: getDefaultConfig
  Purpose:  Fill structure with sensible factory defaults
  Reason:   Used for initial setup and factory reset
*/
void getDefaultConfig(SystemConfig &config);

#endif // STORAGE_H
