// Generated by Copilot
#ifndef WEBSERVER_H
#define WEBSERVER_H

#include <Arduino.h>
#include "config.h"
#include "storage.h"

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Web Server Module Public Functions
// ═══════════════════════════════════════════════════════════════════════════

/*
  Function: initWebServer
  Purpose:  Initialize WiFi connection and start web server
  Reason:   Provides user interface for configuration and control
  Returns:  true if web server started successfully
*/
bool initWebServer(SystemConfig &config);

/*
  Function: updateWebServer
  Purpose:  Handle web server events and client requests
  Reason:   Should be called in main loop to process incoming connections
*/
void updateWebServer();

/*
  Function: startAccessPoint
  Purpose:  Create WiFi access point for initial setup
  Reason:   Allows configuration when home WiFi not yet configured
  Returns:  true if AP started successfully
*/
bool startAccessPoint();

/*
  Function: connectToWiFi
  Purpose:  Connect to configured home WiFi network
  Reason:   Provides internet access for NTP and OTA updates
  Returns:  true if connection successful
*/
bool connectToWiFi(const char *ssid, const char *password);

/*
  Function: isWiFiConnected
  Purpose:  Check current WiFi connection status
  Reason:   Used to determine if reconnection needed
  Returns:  true if connected to WiFi
*/
bool isWiFiConnected();

/*
  Function: getLocalIP
  Purpose:  Get current IP address for display
  Reason:   User needs IP to access web interface
  Returns:  IP address as string
*/
String getLocalIP();

/*
  Function: handleOTA
  Purpose:  Process OTA (Over-The-Air) firmware update
  Reason:   Allows wireless firmware updates without USB connection
*/
void handleOTA();

/*
  Function: getWebServerStatus
  Purpose:  Get current web server state for debug display
  Reason:   Shows connection status on info page
  Returns:  Status string (AP mode, connected, etc.)
*/
String getWebServerStatus();

#endif // WEBSERVER_H
