// Generated by Copilot
#include <Arduino.h>
#include <NTPClient.h>
#include <WiFiUdp.h>
#include "config.h"
#include "storage.h"
#include "sensors.h"
#include "leds.h"
#include "webserver.h"

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Global System State
// ═══════════════════════════════════════════════════════════════════════════

SystemConfig sysConfig;
WiFiUDP ntpUDP;
NTPClient timeClient(ntpUDP, NTP_SERVER, NTP_OFFSET_DEFAULT, NTP_UPDATE_INTERVAL);

// ⚪ NOTE: Timing for main loop control
unsigned long lastLoopTime = 0;
unsigned long lastStatusTime = 0;

// ⚪ NOTE: System state flags
bool systemInitialized = false;
bool lightsDisabledBySchedule = false;

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Setup Function - System Initialization
// ═══════════════════════════════════════════════════════════════════════════

void setup()
{
  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: Initialize Serial Communication
  // ⚪ NOTE: Used for debugging and system monitoring
  // ═══════════════════════════════════════════════════════════════════════

  Serial.begin(SERIAL_BAUD_RATE);
  delay(500); // Allow serial to stabilize

#ifdef DEBUG
  Serial.println(F("\n\n"));
  Serial.println(F("═════════════════════════════════════════════════════════"));
  Serial.println(F("  StairLight System v1.0"));
  Serial.println(F("  ESP8266 Intelligent Stair Lighting"));
  Serial.println(F("═════════════════════════════════════════════════════════"));
  Serial.println();
#endif

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: Initialize Storage and Load Configuration
  // ⚪ NOTE: Must happen first as other modules need config values
  // ═══════════════════════════════════════════════════════════════════════

#ifdef DEBUG
  Serial.println(F("[1/5] Initializing Storage..."));
#endif

  initStorage();
  bool configLoaded = loadConfig(sysConfig);

  if (!configLoaded)
  {
#ifdef DEBUG
    Serial.println(F("  -> Using default configuration"));
#endif
  }

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: Initialize LED System
  // ⚪ NOTE: PCA9685 PWM driver for LED control
  // ═══════════════════════════════════════════════════════════════════════

#ifdef DEBUG
  Serial.println(F("[2/5] Initializing LED System..."));
#endif

  if (!initLEDs())
  {
#ifdef DEBUG
    Serial.println(F("  -> ERROR: LED initialization failed"));
#endif
    // 🟠 WARNING: System cannot function without LEDs
    while (1)
    {
      delay(1000);
    } // Halt execution
  }

  // 🔵 INFO: Apply global brightness from config
  setGlobalBrightness(sysConfig.globalBrightness);

// 🔵 INFO: Run Knight Rider startup animation
#ifdef DEBUG
  Serial.println(F("  -> Starting Knight Rider animation"));
#endif
  startKnightRider();

  // 🔵 INFO: Wait for Knight Rider to complete
  // ⚪ NOTE: Provides visual feedback that system is booting
  while (isEffectRunning())
  {
    updateLEDs();
    delay(20);
  }

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: Initialize Sensor System
  // ⚪ NOTE: MPU6050 accelerometer and bottom sensor
  // ═══════════════════════════════════════════════════════════════════════

#ifdef DEBUG
  Serial.println(F("[3/5] Initializing Sensors..."));
#endif

  if (!initSensors())
  {
#ifdef DEBUG
    Serial.println(F("  -> ERROR: Sensor initialization failed"));
#endif
    // 🟠 WARNING: System cannot function without sensors
    while (1)
    {
      delay(1000);
    } // Halt execution
  }

  // 🔵 INFO: Apply sensor configuration from EEPROM
  setAccelThreshold(sysConfig.sensor.accelThreshold);
  setDebounceDelay(sysConfig.sensor.debounceDelay);
  setEffectTimeout(sysConfig.sensor.effectTimeout);

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: Initialize Web Server
  // ⚪ NOTE: WiFi and HTTP server for configuration interface
  // ═══════════════════════════════════════════════════════════════════════

#ifdef DEBUG
  Serial.println(F("[4/5] Initializing Web Server..."));
#endif

  if (!initWebServer(sysConfig))
  {
#ifdef DEBUG
    Serial.println(F("  -> WARNING: Web server initialization failed"));
    Serial.println(F("  -> Continuing without WiFi..."));
#endif
    // ⚪ NOTE: System can still function locally without WiFi
  }
  else
  {
#ifdef DEBUG
    Serial.print(F("  -> Access web interface at: http://"));
    Serial.println(getLocalIP());
#endif
  }

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: Initialize NTP Time Client
  // ⚪ NOTE: Required for scheduling feature
  // ═══════════════════════════════════════════════════════════════════════

#ifdef DEBUG
  Serial.println(F("[5/5] Initializing Time Synchronization..."));
#endif

  if (isWiFiConnected() && sysConfig.schedule.enabled)
  {
    timeClient.setTimeOffset(sysConfig.schedule.timezoneOffset);
    timeClient.begin();
    timeClient.update();

#ifdef DEBUG
    Serial.print(F("  -> Current time: "));
    Serial.println(timeClient.getFormattedTime());
#endif
  }
  else
  {
#ifdef DEBUG
    Serial.println(F("  -> Scheduling disabled (no WiFi or disabled in config)"));
#endif
  }

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: System Ready
  // ═══════════════════════════════════════════════════════════════════════

  systemInitialized = true;

#ifdef DEBUG
  Serial.println();
  Serial.println(F("═════════════════════════════════════════════════════════"));
  Serial.println(F("  System Initialized Successfully"));
  Serial.println(F("  Ready for Motion Detection"));
  Serial.println(F("═════════════════════════════════════════════════════════"));
  Serial.println();
#endif
}

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Check if Lights Should Be Disabled by Schedule
// ═══════════════════════════════════════════════════════════════════════════

bool checkSchedule()
{
  // 🔵 INFO: Skip check if scheduling disabled
  if (!sysConfig.schedule.enabled)
  {
    return false; // Lights NOT disabled
  }

  // 🔵 INFO: Update time from NTP server
  // ⚪ NOTE: NTPClient handles update intervals internally
  if (isWiFiConnected())
  {
    timeClient.update();
  }

  // 🔵 INFO: Get current hour (0-23)
  int currentHour = timeClient.getHours();

  // 🔵 INFO: Check if current hour is within disable window
  uint8_t startHour = sysConfig.schedule.disableStart;
  uint8_t endHour = sysConfig.schedule.disableEnd;

  bool disabled = false;

  // ⚪ NOTE: Handle normal case (e.g., disable 8-20 = 8AM to 8PM)
  // ⚪ TRICKY: Time range logic handles two cases:
  //    1. Normal case: start < end (e.g., 8-20 means 8am-8pm same day)
  //    2. Wraparound case: start > end (e.g., 20-8 means 8pm today through 8am tomorrow)
  if (startHour < endHour)
  {
    disabled = (currentHour >= startHour && currentHour < endHour);
  }
  // ⚪ NOTE: Handle wraparound case (e.g., disable 20-8 = 8PM to 8AM next day)
  else if (startHour > endHour)
  {
    disabled = (currentHour >= startHour || currentHour < endHour);
  }
  // ⚪ NOTE: If startHour == endHour, scheduling effectively disabled (no time range)

  return disabled;
}

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Main Loop Function
// ═══════════════════════════════════════════════════════════════════════════

void loop()
{
  unsigned long currentTime = millis();

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: Rate Limiting for Main Loop
  // ⚪ NOTE: Prevents excessive CPU usage while maintaining responsiveness
  // ⚪ PERFORMANCE: 50ms interval gives 20 Hz update rate - adequate for motion detection.
  //    Higher rates would waste CPU without improving user experience.
  // ═══════════════════════════════════════════════════════════════════════

  if (currentTime - lastLoopTime < LOOP_UPDATE_INTERVAL)
  {
    delay(10); // Short delay to yield CPU to WiFi stack and background tasks
    return;
  }

  lastLoopTime = currentTime;

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: Update Web Server
  // ⚪ NOTE: Handle HTTP requests and OTA updates
  // ═══════════════════════════════════════════════════════════════════════

  updateWebServer();

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: Update LED Animations
  // ⚪ NOTE: Process current effect frame
  // ═══════════════════════════════════════════════════════════════════════

  updateLEDs();

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: Update Sensor Readings
  // ⚪ NOTE: Read MPU6050 and bottom sensor
  // ═══════════════════════════════════════════════════════════════════════

  updateSensors();

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: Check Scheduling
  // ⚪ NOTE: Determine if lights should be disabled by time of day
  // ═══════════════════════════════════════════════════════════════════════

  bool wasDisabled = lightsDisabledBySchedule;
  lightsDisabledBySchedule = checkSchedule();

  // 🔵 INFO: Log schedule state changes
  if (lightsDisabledBySchedule != wasDisabled)
  {
#ifdef DEBUG
    if (lightsDisabledBySchedule)
    {
      Serial.println(F("Schedule: Lights DISABLED by schedule"));
    }
    else
    {
      Serial.println(F("Schedule: Lights ENABLED by schedule"));
    }
#endif
  }

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: Motion Detection and Effect Triggering
  // ⚪ NOTE: Only process motion if lights not disabled and no effect running
  // ═══════════════════════════════════════════════════════════════════════

  if (!lightsDisabledBySchedule && !isEffectRunning())
  {
    MotionDirection motion = checkMotion();

    if (motion != MotionDirection::NONE)
    {
      // 🔵 INFO: Determine which effect to trigger based on motion direction
      if (motion == MotionDirection::WALK_UP)
      {
#ifdef DEBUG
        Serial.println(F("Motion: Walk-up detected, starting walk-up effect"));
#endif

        if (sysConfig.walkUp.enabled)
        {
          startEffect(EffectType::WALK_UP, sysConfig.walkUp);
        }
      }
      else if (motion == MotionDirection::WALK_DOWN)
      {
#ifdef DEBUG
        Serial.println(F("Motion: Walk-down detected, starting walk-down effect"));
#endif

        if (sysConfig.walkDown.enabled)
        {
          startEffect(EffectType::WALK_DOWN, sysConfig.walkDown);
        }
      }
    }
  }

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: Debug Status Output
  // ⚪ NOTE: Periodic status information when debug mode enabled
  // ═══════════════════════════════════════════════════════════════════════

#ifdef DEBUG
  if (sysConfig.debugMode && currentTime - lastStatusTime > STATUS_UPDATE_INTERVAL)
  {
    lastStatusTime = currentTime;

    Serial.println(F("─────────────────────────────────────────"));
    Serial.println(F("System Status:"));

    // 🔵 INFO: Sensor status
    SensorStatus sensorStatus = getSensorStatus();
    Serial.print(F("  Accel: X="));
    Serial.print(sensorStatus.accelX, 2);
    Serial.print(F(" Y="));
    Serial.print(sensorStatus.accelY, 2);
    Serial.print(F(" Z="));
    Serial.print(sensorStatus.accelZ, 2);
    Serial.print(F(" Mag="));
    Serial.println(sensorStatus.accelMagnitude, 2);

    Serial.print(F("  Bottom Sensor: "));
    Serial.println(sensorStatus.bottomSensorActive ? "ACTIVE" : "Inactive");

    Serial.print(F("  Motion Detected: "));
    Serial.println(sensorStatus.motionDetected ? "YES" : "No");

    // 🔵 INFO: Effect status
    Serial.print(F("  Effect Running: "));
    Serial.println(isEffectRunning() ? "YES" : "No");

    Serial.print(F("  Current State: "));
    Serial.println((uint8_t)getCurrentState());

    // 🔵 INFO: WiFi status
    Serial.print(F("  WiFi: "));
    Serial.println(getWebServerStatus());

    // 🔵 INFO: Schedule status
    Serial.print(F("  Lights: "));
    Serial.println(lightsDisabledBySchedule ? "DISABLED by schedule" : "Enabled");

    // 🔵 INFO: Memory status
    Serial.print(F("  Free Heap: "));
    Serial.print(ESP.getFreeHeap());
    Serial.println(F(" bytes"));

    Serial.println(F("─────────────────────────────────────────"));
  }
#endif
}
