// Generated by Copilot
#include "storage.h"
#include <EEPROM.h>

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: EEPROM Initialization
// ═══════════════════════════════════════════════════════════════════════════

void initStorage()
{
  // 🔵 INFO: Initialize EEPROM with defined size
  // ⚪ NOTE: Required before any read/write operations
  EEPROM.begin(EEPROM_SIZE);

#ifdef DEBUG
  Serial.println(F("Storage: EEPROM initialized"));
#endif
}

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Default Configuration Generator
// ═══════════════════════════════════════════════════════════════════════════

void getDefaultConfig(SystemConfig &config)
{
  // 🔵 INFO: Set validation marker and version
  config.magicNumber = EEPROM_MAGIC_NUMBER;
  config.version = 1;

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: Walk-Up Effect Defaults (bottom sensor triggered)
  // ⚪ NOTE: Lights turn on from bottom to top
  // ═══════════════════════════════════════════════════════════════════════
  config.walkUp.stepDelay = 150;
  config.walkUp.fadeDuration = 500;
  config.walkUp.brightness = 60;
  config.walkUp.overlap = 3;
  config.walkUp.enabled = true;

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: Walk-Down Effect Defaults (top MPU6050 triggered)
  // ⚪ NOTE: Lights turn on from top to bottom
  // ═══════════════════════════════════════════════════════════════════════
  config.walkDown.stepDelay = 150;
  config.walkDown.fadeDuration = 500;
  config.walkDown.brightness = 60;
  config.walkDown.overlap = 3;
  config.walkDown.enabled = true;

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: Walk-Up-Out Effect Defaults (fade out bottom to top)
  // ⚪ NOTE: After timeout, lights turn off from bottom to top
  // ═══════════════════════════════════════════════════════════════════════
  config.walkUpOut.stepDelay = 100;
  config.walkUpOut.fadeDuration = 600;
  config.walkUpOut.brightness = 0; // Not used for off effect
  config.walkUpOut.overlap = 2;
  config.walkUpOut.enabled = true;

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: Walk-Down-Out Effect Defaults (fade out top to bottom)
  // ⚪ NOTE: After timeout, lights turn off from top to bottom
  // ═══════════════════════════════════════════════════════════════════════
  config.walkDownOut.stepDelay = 100;
  config.walkDownOut.fadeDuration = 600;
  config.walkDownOut.brightness = 0; // Not used for off effect
  config.walkDownOut.overlap = 2;
  config.walkDownOut.enabled = true;

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: WiFi Configuration Defaults
  // ⚪ NOTE: Set your WiFi credentials here for development
  // ═══════════════════════════════════════════════════════════════════════
  // strncpy(config.wifi.ssid, "MIA_2", MAX_SSID_LENGTH);
  // strncpy(config.wifi.password, "12345mia12345", MAX_PASSWORD_LENGTH);
  strncpy(config.wifi.ssid, "FRITZ!Box 7590 SI", MAX_SSID_LENGTH);
  strncpy(config.wifi.password, "71410429904393153581", MAX_PASSWORD_LENGTH);
  config.wifi.ssid[MAX_SSID_LENGTH] = '\0';
  config.wifi.password[MAX_PASSWORD_LENGTH] = '\0';
  config.wifi.useHomeWiFi = true;

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: Scheduling Configuration Defaults
  // ⚪ NOTE: Disabled by default, allows 24/7 operation initially
  // ═══════════════════════════════════════════════════════════════════════
  config.schedule.enabled = false;
  config.schedule.disableStart = DISABLE_START_HOUR;
  config.schedule.disableEnd = DISABLE_END_HOUR;
  config.schedule.timezoneOffset = NTP_OFFSET_DEFAULT;

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: Sensor Configuration Defaults
  // ⚪ NOTE: Balanced sensitivity for typical staircase
  // ═══════════════════════════════════════════════════════════════════════
  config.sensor.accelThreshold = ACCEL_THRESHOLD_DEFAULT;
  config.sensor.effectTimeout = EFFECT_TIMEOUT_DEFAULT;
  config.sensor.debounceDelay = SENSOR_DEBOUNCE_MS;

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: Global System Defaults
  // ═══════════════════════════════════════════════════════════════════════
  config.debugMode = true; // Debug mode ON by default
  config.globalBrightness = BRIGHTNESS_DEFAULT;

#ifdef DEBUG
  Serial.println(F("Storage: Default configuration generated"));
#endif
}

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Load Configuration from EEPROM
// ═══════════════════════════════════════════════════════════════════════════

bool loadConfig(SystemConfig &config)
{
  // 🔵 INFO: Read configuration structure from EEPROM
  // ⚪ NOTE: EEPROM.get() handles multi-byte reads automatically
  EEPROM.get(EEPROM_CONFIG_START, config);

  // 🔵 INFO: Validate magic number to detect uninitialized EEPROM
  // ⚪ NOTE: If invalid, we'll use defaults instead
  if (config.magicNumber != EEPROM_MAGIC_NUMBER)
  {
#ifdef DEBUG
    Serial.println(F("Storage: Invalid magic number, using defaults"));
#endif

    getDefaultConfig(config);
    saveConfig(config); // Save defaults for next boot
    return false;
  }

  // 🟠 WARNING: Version mismatch handling could be added here
  // ⚪ NOTE: For now, we trust the structure matches

#ifdef DEBUG
  Serial.println(F("Storage: Configuration loaded from EEPROM"));
  Serial.print(F("  - WiFi SSID: "));
  Serial.println(config.wifi.ssid);
  Serial.print(F("  - Debug Mode: "));
  Serial.println(config.debugMode ? "ON" : "OFF");
#endif

  return true;
}

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Save Configuration to EEPROM
// ═══════════════════════════════════════════════════════════════════════════

bool saveConfig(const SystemConfig &config)
{
  // 🔵 INFO: Write entire configuration structure to EEPROM
  // ⚪ NOTE: EEPROM.put() handles multi-byte writes and wear leveling
  EEPROM.put(EEPROM_CONFIG_START, config);

  // 🔵 INFO: Commit changes to flash memory
  // ⚪ NOTE: Required for ESP8266 to actually persist the data
  bool success = EEPROM.commit();

#ifdef DEBUG
  if (success)
  {
    Serial.println(F("Storage: Configuration saved to EEPROM"));
  }
  else
  {
    Serial.println(F("Storage: ERROR - Failed to save configuration"));
  }
#endif

  return success;
}

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Factory Reset Function
// ═══════════════════════════════════════════════════════════════════════════

void resetToDefaults(SystemConfig &config)
{
#ifdef DEBUG
  Serial.println(F("Storage: Performing factory reset"));
#endif

  // 🔵 INFO: Load default values into configuration
  getDefaultConfig(config);

  // 🔵 INFO: Persist defaults to EEPROM
  saveConfig(config);

#ifdef DEBUG
  Serial.println(F("Storage: Factory reset complete"));
#endif
}
