// Generated by Copilot
#include "webserver.h"
#include "sensors.h"
#include "leds.h"
#include <ESP8266WiFi.h>
#include <ESPAsyncTCP.h>
#include <ArduinoOTA.h>
#include <ArduinoJson.h>
#include <LittleFS.h>

// 🔵 INFO: Define HTTP methods if not already defined
#ifndef HTTP_GET
typedef enum
{
  HTTP_GET = 0b00000001,
  HTTP_POST = 0b00000010,
  HTTP_DELETE = 0b00000100,
  HTTP_PUT = 0b00001000,
  HTTP_PATCH = 0b00010000,
  HTTP_HEAD = 0b00100000,
  HTTP_OPTIONS = 0b01000000,
  HTTP_ANY = 0b01111111,
} WebRequestMethod;
#endif

#include <ESPAsyncWebServer.h>

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Global Web Server Objects
// ═══════════════════════════════════════════════════════════════════════════

AsyncWebServer server(WEB_SERVER_PORT);
SystemConfig *globalConfig = nullptr; // Pointer to main config

// ⚪ NOTE: WiFi connection state
bool wifiConnected = false;
unsigned long lastWiFiCheck = 0;

// ⚪ NOTE: Request body accumulator for chunked POST requests
static String requestBody = "";

// ⚪ NOTE: External functions from other modules (forward declarations)
extern void setAccelThreshold(float threshold);
extern void setDebounceDelay(unsigned long delayMs);
extern void setGlobalBrightness(uint8_t brightness);
extern void setEffectTimeout(unsigned long timeoutMs);
extern SensorStatus getSensorStatus();
extern EffectState getCurrentState();
extern bool isEffectRunning();
extern void startEffect(EffectType type, const EffectConfig &config);
extern void stopAllEffects();
extern void resetLastTrigger();

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: WiFi Access Point Setup
// ═══════════════════════════════════════════════════════════════════════════

bool startAccessPoint()
{
#ifdef DEBUG
  Serial.println(F("WebServer: Starting Access Point mode"));
  Serial.print(F("  - SSID: "));
  Serial.println(AP_SSID);
#endif

  // 🔵 INFO: Configure and start access point
  // ⚪ NOTE: Provides local network for initial configuration
  WiFi.mode(WIFI_AP);
  bool success = WiFi.softAP(AP_SSID, AP_PASSWORD);

  if (success)
  {
    IPAddress ip = WiFi.softAPIP();
#ifdef DEBUG
    Serial.print(F("  - IP Address: "));
    Serial.println(ip);
#endif
    wifiConnected = true;
  }

  return success;
}

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: WiFi Station Mode Connection
// ═══════════════════════════════════════════════════════════════════════════

bool connectToWiFi(const char *ssid, const char *password)
{
#ifdef DEBUG
  Serial.print(F("WebServer: Connecting to WiFi: "));
  Serial.println(ssid);
#endif

  // 🔵 INFO: Switch to station mode and attempt connection
  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);

  // 🔵 INFO: Wait for connection with timeout
  unsigned long startTime = millis();
  while (WiFi.status() != WL_CONNECTED && millis() - startTime < WIFI_CONNECT_TIMEOUT)
  {
    delay(500);
#ifdef DEBUG
    Serial.print(F("."));
#endif
  }

#ifdef DEBUG
  Serial.println();
#endif

  // 🔵 INFO: Check connection result
  if (WiFi.status() == WL_CONNECTED)
  {
    wifiConnected = true;
#ifdef DEBUG
    Serial.println(F("WebServer: WiFi connected successfully"));
    Serial.print(F("  - IP Address: "));
    Serial.println(WiFi.localIP());
#endif
    return true;
  }
  else
  {
    wifiConnected = false;
#ifdef DEBUG
    Serial.println(F("WebServer: WiFi connection failed"));
#endif
    return false;
  }
}

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Helper Function - Convert EffectType to JSON Key
// ═══════════════════════════════════════════════════════════════════════════

const char *effectTypeToString(EffectType type)
{
  switch (type)
  {
  case EffectType::WALK_UP:
    return "walkUp";
  case EffectType::WALK_DOWN:
    return "walkDown";
  case EffectType::WALK_UP_OUT:
    return "walkUpOut";
  case EffectType::WALK_DOWN_OUT:
    return "walkDownOut";
  default:
    return "unknown";
  }
}

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Helper Function - Create Effect JSON Object
// ═══════════════════════════════════════════════════════════════════════════

void effectToJson(JsonObject obj, const EffectConfig &effect)
{
  obj["stepDelay"] = effect.stepDelay;
  obj["fadeDuration"] = effect.fadeDuration;
  obj["brightness"] = effect.brightness;
  obj["overlap"] = effect.overlap;
  obj["enabled"] = effect.enabled;
}

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Helper Function - Parse Effect from JSON
// ═══════════════════════════════════════════════════════════════════════════

void jsonToEffect(EffectConfig &effect, JsonObjectConst obj)
{
  if (obj["stepDelay"].is<int>())
    effect.stepDelay = obj["stepDelay"];
  if (obj["fadeDuration"].is<int>())
    effect.fadeDuration = obj["fadeDuration"];
  if (obj["brightness"].is<int>())
    effect.brightness = obj["brightness"];
  if (obj["overlap"].is<int>())
    effect.overlap = obj["overlap"];
  if (obj["enabled"].is<bool>())
    effect.enabled = obj["enabled"];
}

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Web Server Route Handlers
// ═══════════════════════════════════════════════════════════════════════════

void setupRoutes()
{
  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: Serve static files from LittleFS
  // ⚪ NOTE: HTML, CSS, JS files for web interface
  // ═══════════════════════════════════════════════════════════════════════

  server.serveStatic("/", LittleFS, "/").setDefaultFile("index.html");

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: GET /api/status - Current system status
  // ═══════════════════════════════════════════════════════════════════════

  server.on("/api/status", HTTP_GET, [](AsyncWebServerRequest *request)
            {
    JsonDocument doc;
    
    // 🔵 INFO: System state
    doc["effectRunning"] = isEffectRunning();
    doc["currentState"] = (uint8_t)getCurrentState();
    
    // 🔵 INFO: Sensor readings (if debug mode enabled)
    if (globalConfig->debugMode) {
      SensorStatus sensorStatus = getSensorStatus();
      JsonObject sensors = doc["sensors"].to<JsonObject>();
      sensors["accelX"] = sensorStatus.accelX;
      sensors["accelY"] = sensorStatus.accelY;
      sensors["accelZ"] = sensorStatus.accelZ;
      sensors["accelMagnitude"] = sensorStatus.accelMagnitude;
      sensors["bottomSensor"] = sensorStatus.bottomSensorActive;
      sensors["motionDetected"] = sensorStatus.motionDetected;
    }
    
    // 🔵 INFO: WiFi information
    doc["wifiConnected"] = wifiConnected;
    doc["ipAddress"] = getLocalIP();
    doc["rssi"] = WiFi.RSSI();
    
    String response;
    serializeJson(doc, response);
    request->send(200, "application/json", response); });

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: GET /api/config - Get complete configuration
  // ═══════════════════════════════════════════════════════════════════════

  server.on("/api/config", HTTP_GET, [](AsyncWebServerRequest *request)
            {
    JsonDocument doc;
    
    // 🔵 INFO: Effect configurations
    JsonObject effects = doc["effects"].to<JsonObject>();
    effectToJson(effects["walkUp"].to<JsonObject>(), globalConfig->walkUp);
    effectToJson(effects["walkDown"].to<JsonObject>(), globalConfig->walkDown);
    effectToJson(effects["walkUpOut"].to<JsonObject>(), globalConfig->walkUpOut);
    effectToJson(effects["walkDownOut"].to<JsonObject>(), globalConfig->walkDownOut);
    
    // 🔵 INFO: WiFi configuration (don't send password)
    JsonObject wifi = doc["wifi"].to<JsonObject>();
    wifi["ssid"] = globalConfig->wifi.ssid;
    wifi["useHomeWiFi"] = globalConfig->wifi.useHomeWiFi;
    
    // 🔵 INFO: Scheduling configuration
    JsonObject schedule = doc["schedule"].to<JsonObject>();
    schedule["enabled"] = globalConfig->schedule.enabled;
    schedule["disableStart"] = globalConfig->schedule.disableStart;
    schedule["disableEnd"] = globalConfig->schedule.disableEnd;
    schedule["timezoneOffset"] = globalConfig->schedule.timezoneOffset;
    
    // 🔵 INFO: Sensor configuration
    JsonObject sensor = doc["sensor"].to<JsonObject>();
    sensor["accelThreshold"] = globalConfig->sensor.accelThreshold;
    sensor["effectTimeout"] = globalConfig->sensor.effectTimeout;
    sensor["debounceDelay"] = globalConfig->sensor.debounceDelay;
    
    // 🔵 INFO: Global settings
    doc["debugMode"] = globalConfig->debugMode;
    doc["globalBrightness"] = globalConfig->globalBrightness;
    
    String response;
    serializeJson(doc, response);
    request->send(200, "application/json", response); });

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: POST /api/config - Update configuration
  // ═══════════════════════════════════════════════════════════════════════

  server.on("/api/config", HTTP_POST, [](AsyncWebServerRequest *request) {}, NULL, [](AsyncWebServerRequest *request, uint8_t *data, size_t len, size_t index, size_t total)
            {
      
      // 🔵 INFO: Accumulate chunked body data
      if (index == 0) {
        requestBody = "";  // Start new request
        requestBody.reserve(total);
      }
      
      // Add this chunk to the body
      for (size_t i = 0; i < len; i++) {
        requestBody += (char)data[i];
      }
      
      // 🔵 INFO: Wait until all chunks received
      if (index + len != total) {
#ifdef DEBUG
        Serial.printf("WebServer: Received chunk %u/%u (%u bytes)\n", index + len, total, len);
#endif
        return;
      }

    // 🔵 INFO: All chunks received, now parse
#ifdef DEBUG
      Serial.printf("WebServer: Complete body received (%u bytes)\n", requestBody.length());
      Serial.println(requestBody);
#endif
      
      JsonDocument doc;
      DeserializationError error = deserializeJson(doc, requestBody);
      
      if (error) {
#ifdef DEBUG
        Serial.print(F("WebServer: JSON parse error: "));
        Serial.println(error.c_str());
#endif
        String errorMsg = "{\"error\":\"Invalid JSON\",\"message\":\"";
        errorMsg += error.c_str();
        errorMsg += "\"}";
        request->send(400, "application/json", errorMsg);
        return;
      }

#ifdef DEBUG
      Serial.println(F("WebServer: Parsed config update:"));
      serializeJsonPretty(doc, Serial);
      Serial.println();
#endif
      
      // 🔵 INFO: Update effect configurations
      if (doc["effects"].is<JsonObject>())
      {
        JsonObjectConst effects = doc["effects"];
        if (effects["walkUp"].is<JsonObject>())
          jsonToEffect(globalConfig->walkUp, effects["walkUp"]);
        if (effects["walkDown"].is<JsonObject>())
          jsonToEffect(globalConfig->walkDown, effects["walkDown"]);
        if (effects["walkUpOut"].is<JsonObject>())
          jsonToEffect(globalConfig->walkUpOut, effects["walkUpOut"]);
        if (effects["walkDownOut"].is<JsonObject>())
          jsonToEffect(globalConfig->walkDownOut, effects["walkDownOut"]);
      }

      // 🔵 INFO: Update WiFi configuration
      if (doc["wifi"].is<JsonObject>())
      {
        JsonObjectConst wifi = doc["wifi"];
        if (wifi["ssid"].is<const char *>())
        {
          strncpy(globalConfig->wifi.ssid, wifi["ssid"], MAX_SSID_LENGTH);
          globalConfig->wifi.ssid[MAX_SSID_LENGTH] = '\0';
        }
        if (wifi["password"].is<const char *>())
        {
          strncpy(globalConfig->wifi.password, wifi["password"], MAX_PASSWORD_LENGTH);
          globalConfig->wifi.password[MAX_PASSWORD_LENGTH] = '\0';
        }
        if (wifi["useHomeWiFi"].is<bool>())
        {
          globalConfig->wifi.useHomeWiFi = wifi["useHomeWiFi"];
        }
      }

      // 🔵 INFO: Update scheduling configuration
      if (doc["schedule"].is<JsonObject>())
      {
        JsonObjectConst schedule = doc["schedule"];
        if (schedule["enabled"].is<bool>())
          globalConfig->schedule.enabled = schedule["enabled"];
        if (schedule["disableStart"].is<int>())
          globalConfig->schedule.disableStart = schedule["disableStart"];
        if (schedule["disableEnd"].is<int>())
          globalConfig->schedule.disableEnd = schedule["disableEnd"];
        if (schedule["timezoneOffset"].is<int>())
          globalConfig->schedule.timezoneOffset = schedule["timezoneOffset"];
      }

      // 🔵 INFO: Update sensor configuration and apply immediately
      if (doc["sensor"].is<JsonObject>())
      {
        JsonObjectConst sensor = doc["sensor"];
        if (sensor["accelThreshold"].is<float>())
        {
          globalConfig->sensor.accelThreshold = sensor["accelThreshold"];
          setAccelThreshold(globalConfig->sensor.accelThreshold);
        }
        if (sensor["effectTimeout"].is<unsigned long>())
        {
          globalConfig->sensor.effectTimeout = sensor["effectTimeout"];
          setEffectTimeout(globalConfig->sensor.effectTimeout);
        }
        if (sensor["debounceDelay"].is<unsigned long>())
        {
          globalConfig->sensor.debounceDelay = sensor["debounceDelay"];
          setDebounceDelay(globalConfig->sensor.debounceDelay);
        }
      }

      // 🔵 INFO: Update global settings and apply immediately
      if (doc["debugMode"].is<bool>())
      {
        globalConfig->debugMode = doc["debugMode"];
      }
      if (doc["globalBrightness"].is<int>())
      {
        globalConfig->globalBrightness = doc["globalBrightness"];
        setGlobalBrightness(globalConfig->globalBrightness);
      }
      
      // 🔵 INFO: Save configuration to EEPROM
      bool saved = saveConfig(*globalConfig);

#ifdef DEBUG
      Serial.print(F("WebServer: Config save result: "));
      Serial.println(saved ? "SUCCESS" : "FAILED");
#endif
      
      if (saved) {
        request->send(200, "application/json", "{\"success\":true}");
      } else {
        request->send(500, "application/json", "{\"error\":\"Failed to save config\",\"message\":\"EEPROM write failed\"}");
      } });

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: POST /api/reset - Factory reset
  // ═══════════════════════════════════════════════════════════════════════

  server.on("/api/reset", HTTP_POST, [](AsyncWebServerRequest *request)
            {
              resetToDefaults(*globalConfig);
              request->send(200, "application/json", "{\"success\":true}");

// 🟠 WARNING: Consider restarting ESP after factory reset
#ifdef DEBUG
              Serial.println(F("WebServer: Factory reset requested"));
#endif
            });

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: POST /api/test - Manual effect trigger for testing
  // ═══════════════════════════════════════════════════════════════════════

  server.on("/api/test", HTTP_POST, [](AsyncWebServerRequest *request) {}, NULL, [](AsyncWebServerRequest *request, uint8_t *data, size_t len, size_t index, size_t total)
            {
      JsonDocument doc;
      DeserializationError error = deserializeJson(doc, data, len);
      
      if (error || !doc["effectType"].is<int>()) {
        request->send(400, "application/json", "{\"error\":\"Invalid request\"}");
        return;
      }
      
      uint8_t effectType = doc["effectType"];
      EffectType type = static_cast<EffectType>(effectType);
      
      // 🔵 INFO: Select configuration based on effect type
      EffectConfig* config = nullptr;
      switch (type) {
        case EffectType::WALK_UP: config = &globalConfig->walkUp; break;
        case EffectType::WALK_DOWN: config = &globalConfig->walkDown; break;
        case EffectType::WALK_UP_OUT: config = &globalConfig->walkUpOut; break;
        case EffectType::WALK_DOWN_OUT: config = &globalConfig->walkDownOut; break;
      }
      
      if (config) {
        startEffect(type, *config);
        request->send(200, "application/json", "{\"success\":true}");
      } else {
        request->send(400, "application/json", "{\"error\":\"Invalid effect type\"}");
      } });

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: POST /api/install/bottom - Toggle bottom sensor install mode
  // ═══════════════════════════════════════════════════════════════════════

  server.on("/api/install/bottom", HTTP_POST, [](AsyncWebServerRequest *request) {}, NULL, [](AsyncWebServerRequest *request, uint8_t *data, size_t len, size_t index, size_t total)
            {
              JsonDocument doc;
              DeserializationError error = deserializeJson(doc, data, len);

              if (error || !doc["enabled"].is<bool>())
              {
                request->send(400, "application/json", "{\"error\":\"Invalid request\"}");
                return;
              }

              bool enabled = doc["enabled"];
              setBottomSensorInstallMode(enabled);

              request->send(200, "application/json", "{\"success\":true}");

#ifdef DEBUG
              Serial.print(F("WebServer: Bottom sensor install mode set to "));
              Serial.println(enabled ? F("ON") : F("OFF"));
#endif
            });

  // ═══════════════════════════════════════════════════════════════════════
  // 🔵 INFO: POST /api/install/motion - Toggle motion sensor install mode
  // ═══════════════════════════════════════════════════════════════════════

  server.on("/api/install/motion", HTTP_POST, [](AsyncWebServerRequest *request) {}, NULL, [](AsyncWebServerRequest *request, uint8_t *data, size_t len, size_t index, size_t total)
            {
              JsonDocument doc;
              DeserializationError error = deserializeJson(doc, data, len);

              if (error || !doc["enabled"].is<bool>())
              {
                request->send(400, "application/json", "{\"error\":\"Invalid request\"}");
                return;
              }

              bool enabled = doc["enabled"];
              setMotionInstallMode(enabled);

              request->send(200, "application/json", "{\"success\":true}");

#ifdef DEBUG
              Serial.print(F("WebServer: Motion sensor install mode set to "));
              Serial.println(enabled ? F("ON") : F("OFF"));
#endif
            });
}

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: OTA (Over-The-Air) Update Setup
// ═══════════════════════════════════════════════════════════════════════════

void setupOTA()
{
  // 🔵 INFO: Configure OTA hostname
  ArduinoOTA.setHostname(OTA_HOSTNAME);

  // 🔵 INFO: OTA event handlers for debugging
  ArduinoOTA.onStart([]()
                     {
    String type = (ArduinoOTA.getCommand() == U_FLASH) ? "firmware" : "filesystem";
#ifdef DEBUG
    Serial.print(F("OTA: Starting update - "));
    Serial.println(type);
#endif
    
    // 🔵 INFO: Stop all effects during update
    stopAllEffects(); });

  ArduinoOTA.onEnd([]()
                   {
#ifdef DEBUG
                     Serial.println(F("\nOTA: Update complete"));
#endif
                   });

  ArduinoOTA.onProgress([](unsigned int progress, unsigned int total)
                        {
#ifdef DEBUG
                          Serial.printf("OTA Progress: %u%%\r", (progress / (total / 100)));
#endif
                        });

  ArduinoOTA.onError([](ota_error_t error)
                     {
#ifdef DEBUG
                       Serial.printf("OTA Error[%u]: ", error);
                       if (error == OTA_AUTH_ERROR)
                         Serial.println(F("Auth Failed"));
                       else if (error == OTA_BEGIN_ERROR)
                         Serial.println(F("Begin Failed"));
                       else if (error == OTA_CONNECT_ERROR)
                         Serial.println(F("Connect Failed"));
                       else if (error == OTA_RECEIVE_ERROR)
                         Serial.println(F("Receive Failed"));
                       else if (error == OTA_END_ERROR)
                         Serial.println(F("End Failed"));
#endif
                     });

  ArduinoOTA.begin();

#ifdef DEBUG
  Serial.println(F("OTA: Ready for updates"));
#endif
}

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Web Server Initialization
// ═══════════════════════════════════════════════════════════════════════════

bool initWebServer(SystemConfig &config)
{
  globalConfig = &config;

#ifdef DEBUG
  Serial.println(F("WebServer: Initializing..."));
#endif

  // 🔵 INFO: Initialize LittleFS for web files
  delay(100); // Give system time to stabilize
  if (!LittleFS.begin())
  {
#ifdef DEBUG
    Serial.println(F("WebServer: ERROR - LittleFS mount failed"));
    Serial.println(F("WebServer: Attempting to format..."));
#endif
    // Try formatting and mounting again
    if (LittleFS.format())
    {
#ifdef DEBUG
      Serial.println(F("WebServer: Format successful, trying mount again..."));
#endif
      if (LittleFS.begin())
      {
#ifdef DEBUG
        Serial.println(F("WebServer: LittleFS mounted after format"));
#endif
      }
      else
      {
#ifdef DEBUG
        Serial.println(F("WebServer: LittleFS mount failed even after format"));
#endif
      }
    }
  }
  else
  {
#ifdef DEBUG
    Serial.println(F("WebServer: LittleFS mounted successfully"));
#endif
  }

  // 🔵 INFO: Setup WiFi connection
  bool wifiSuccess = false;
  if (config.wifi.useHomeWiFi && strlen(config.wifi.ssid) > 0)
  {
    wifiSuccess = connectToWiFi(config.wifi.ssid, config.wifi.password);

    // 🔵 INFO: Fall back to AP mode if connection fails
    if (!wifiSuccess)
    {
      // show all wifi networks for debugging
      int n = WiFi.scanNetworks();
      Serial.println(F("WebServer: Available WiFi networks:"));
      for (int i = 0; i < n; ++i)
      {
        Serial.print("  ");
        Serial.print(i + 1);
        Serial.print(": ");
        Serial.print(WiFi.SSID(i));
        Serial.print(" (");
        Serial.print(WiFi.RSSI(i));
        Serial.println(" dBm)");
      }

#ifdef DEBUG
      Serial.println(F("WebServer: Home WiFi failed, starting AP mode"));
#endif
      wifiSuccess = startAccessPoint();
    }
  }
  else
  {
    // 🔵 INFO: Start in AP mode for initial setup
    wifiSuccess = startAccessPoint();
  }

  if (!wifiSuccess)
  {
#ifdef DEBUG
    Serial.println(F("WebServer: ERROR - WiFi initialization failed"));
#endif
    return false;
  }

  // 🔵 INFO: Setup web server routes
  setupRoutes();

  // 🔵 INFO: Start web server
  server.begin();

#ifdef DEBUG
  Serial.println(F("WebServer: HTTP server started"));
#endif

  // 🔵 INFO: Setup OTA updates if connected to home WiFi
  if (config.wifi.useHomeWiFi && wifiConnected)
  {
    setupOTA();
  }

  return true;
}

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Web Server Update (Called in Main Loop)
// ═══════════════════════════════════════════════════════════════════════════

void updateWebServer()
{
  // 🔵 INFO: Handle OTA updates
  ArduinoOTA.handle();

  // 🔵 INFO: Check WiFi connection periodically and reconnect if needed
  unsigned long currentTime = millis();
  if (currentTime - lastWiFiCheck > WIFI_RECONNECT_INTERVAL)
  {
    lastWiFiCheck = currentTime;

    if (globalConfig->wifi.useHomeWiFi && WiFi.status() != WL_CONNECTED)
    {
#ifdef DEBUG
      Serial.println(F("WebServer: WiFi disconnected, attempting reconnect..."));
#endif
      connectToWiFi(globalConfig->wifi.ssid, globalConfig->wifi.password);
    }
  }
}

// ═══════════════════════════════════════════════════════════════════════════
// 🔵 INFO: Helper Functions
// ═══════════════════════════════════════════════════════════════════════════

void handleOTA()
{
  ArduinoOTA.handle();
}

bool isWiFiConnected()
{
  return WiFi.status() == WL_CONNECTED;
}

String getLocalIP()
{
  if (WiFi.getMode() == WIFI_AP)
  {
    return WiFi.softAPIP().toString();
  }
  else
  {
    return WiFi.localIP().toString();
  }
}

String getWebServerStatus()
{
  if (WiFi.getMode() == WIFI_AP)
  {
    return "AP Mode: " + String(AP_SSID);
  }
  else if (isWiFiConnected())
  {
    return "Connected: " + String(globalConfig->wifi.ssid);
  }
  else
  {
    return "Disconnected";
  }
}
